version: '3.8'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - ./tmp/data/db:/data/db

  dml_backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - ./:/app
        - /app/node_modules
    ports:
        - "3000:3000"
    depends_on:
        - db
    environment:
        MONGO_URI: mongodb://db:27017/demo
    tty: true
    stdin_open: true